version: "3.8"
services:

  explorer:
    build: .
    volumes:
      - .:/explorer
    environment:
      WORKER_URL: "http://localhost:8080/local"
      BRIDGE_URL: "http://localhost:4000/local/graphql"
    ports:
      - 3000:3000

  bridge:
    build: ../companion-bridge
    volumes:
        - ../companion-bridge:/bridge
    ports:
      - '4000:4000'

  worker:
    build: ../companion-worker
    volumes:
        - ../companion-worker:/worker
    ports:
      - '8080:8080'