on: push
name: Publish on Netlify
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: npm install
    - run: npm run build

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist --branch=${{ steps.vars.outputs.short_ref }}
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}